---
- name: Install RustDesk Server
  when: install_server
  block:
    - name: Download RustDesk server install script
      ansible.builtin.get_url:
        url: "https://raw.githubusercontent.com/techahold/rustdeskinstall/master/install.sh"
        dest: "/tmp/install.sh"
        mode: '0755'

    - name: Run RustDesk server install script with pre-defined answers
      ansible.builtin.expect: 
        command: /tmp/install.sh
        responses:
          'Choose your preferred connection method: auto-resolve current WAN IP or enter your DNS/Domain:': '1'
          'Please choose if you want to download configs and install HTTP server:': '2'
          'waiting for the keypress': '\n'
      become: true
      register: install_output

    - name: Print the install output to the console
      ansible.builtin.debug:
        msg: "install output is: {{ install_output.stdout }}"

    - name: Extract and clean the public key from the output
      ansible.builtin.set_fact:
        rustdesk_public_key: "{{ install_output.stdout | regex_search('Your public key is ([A-Za-z0-9+\/=]+)', '\\1') | first }}"


    - name: Print the extracted public key to the console
      ansible.builtin.debug:
        msg: "The public key is: {{ rustdesk_public_key[0] }}"

    - name: Save the public key to a file in the home directory
      ansible.builtin.copy:
        dest: "/home/{{ ansible_user }}/rustdesk_public_key.txt" 
        content: "{{ rustdesk_public_key }}"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0644'

- name: Install RustDesk Client
  when: install_client
  block:
    - name: Download RustDesk client package
      ansible.builtin.get_url:
        url: "https://github.com/rustdesk/rustdesk/releases/download/1.3.8/rustdesk-1.3.8-x86_64.deb"
        dest: "/tmp/rustdesk.deb"

    - name: Install RustDesk client package
      ansible.builtin.apt:
        deb: "/tmp/rustdesk.deb"
        force: yes
      become: true
